graph TD
  program-->packageConf
  parser-->CONFIG{CONFIG}
  CONFIG{CONFIG}-->PROJECT_DIR{PROJECT_DIR}
  jsArch((jsArch))-->CONFIG{CONFIG}
  jsArch((jsArch))-->EOL{EOL}
  jsArch((jsArch))-->glob
  jsArch((jsArch))-->fs
  jsArch((jsArch))-->parser
  jsArch((jsArch))-->log
  classDef jsarch fill:#e7cdd2,stroke:#ebd4cb,stroke-width:1px,color:#000;
  classDef config fill:#d4cdcc,stroke:#ebd4cb,stroke-width:1px,color:#000;
  classDef others fill:#ebd4cb,stroke:#000,stroke-width:1px,color:#000;
  class program others;
  class packageConf others;
  class CONFIG config;
  class parser others;
  class PROJECT_DIR config;
  class jsArch jsarch;
  class EOL config;
  class glob others;
  class fs others;
  class log others;